### ISSUE TITLE
Our work language

### ISSUE THREAD

**Issue by mikejihbe** [MustWin/lovabletech-devops#4]
<img width="1184" alt="devops___lovable_tech" src="https://user-images.githubusercontent.com/52534/35123527-62757444-fc57-11e7-9f20-bed2ecab1fb0.png">

# Left section
We craft workflow automation solutions to improve quality and decrease time to market.

# Middle section
Let's swap this out with customer testimonials. Get them from Wil/Brandon. Include Craig's from oracle

# Right section
Lovable Tech has experience creating solutions for companies large and small fitted to your engineering needs. We do cloud migrations, Continuous Integration (CI), Continuous Delivery (CD), Containerization, infrastructure provisioning, security, and more.

**Comment by tenji240** [comment]
Updated & Live
