### ISSUE TITLE
Our product partnerships language

### ISSUE THREAD

**Issue by mikejihbe** [MustWin/lovabletech-devops#7]
# subheader:
Lovable.Tech offers unparalleled expertise in DevOps.

# Hashicorp
"We work with Hashicorp on a variety of development projects, using their software to bring our customers real value." -> We're an official Hashicorp solutions integrator.

# Kubernetes
Kubernetes (K8s) is an open-source system for automating deployment, scaling and management of containerized applications. It's one of our preferred platforms and we have made contributions in our client work.

# Apache Mesos --> Mesosphere
Mesosphere develops a suite of technologies for clustered computing solutions. We've built several mesos frameworks and use their technologies extensively.

# Docker
(move this to the leftmost item in the second row)
Docker is a very popular containerization solution and we use it all the time. We're also an official Docker solutions integrtor

**Comment by tenji240** [comment]
Updated
